name: Manually triggered offboarding workflow
on:
  repository_dispatch:
    types: ["offboard"]

jobs:
  offboard:
    runs-on: ubuntu-latest
    steps:
      - name: "Get repo"
        uses: actions/checkout@v3
      - name: location
        run: pwd
      - name: files
        run: ls -la
      - name: environment
        run: env
      - name: Run the flow
        id: offboard
        uses: jbharter/eng_meta-butler@develop
        with:
          action: ${{ github.job }}
      - name: Get output
        run: echo "The action was ${{ steps.run_automation.outputs.action }}"
      - name: Get output
        run: echo "The action was ${{ steps.run_automation.outputs.foo }}"
      - name: Get output
        run: echo "The action was ${{ steps.run_automation.outputs.core }}"
      - name: Get output
        run: echo "The users are ${{join(steps.run_automation.outputs.users.*, '-')}}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ steps.run_automation.outputs.action }}/${{join(steps.run_automation.outputs.users.*, '-')}}
#        with:
#          event_type: ${{ github.event_type }}
